Feat/site layout
effgenij/TaskManager pull request #8
Opened 2022-09-25 21:13 UTC by effgenij

Added bsica site layout and controllers

2022-09-26 06:08 UTC, greybutton requested changes

2022-09-26 06:08 UTC, greybutton commented on app/models/task.rb
> +  state_machine initial: :new_task do
Код от предыдущего задания

Нужно спулить с ребейсом девелоп, и потом отребейсить фича ветку от девелопа

2022-09-28 13:57 UTC, effgenij commented on app/models/task.rb
> +  state_machine initial: :new_task do
Я сделал, но мне кажется что то прошло не так как надо.

2022-09-28 18:29 UTC, greybutton commented on app/models/task.rb
> +  state_machine initial: :new_task do
какие команды выполнял?

2022-09-28 19:31 UTC, effgenij commented on app/models/task.rb
> +  state_machine initial: :new_task do
git pull из develop ветки, git rebase develop из фичи ветки

2022-09-28 19:58 UTC, greybutton commented on app/models/task.rb
> +  state_machine initial: :new_task do
выглядит что пулл без ребейса был в фича ветке 

попробуй так
```
git switch develop
git pull --rebase
git switch feat/site-layout
git rebase develop
```

2022-09-28 20:21 UTC, effgenij commented on app/models/task.rb
> +  state_machine initial: :new_task do
Все. Поправил.

2022-09-29 06:05 UTC, greybutton approved these changes

2022-09-29 06:08 UTC, merged